apiVersion: v1
kind: Secret
metadata:
  name: cme-task-secret
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "Taskproject%cme123"
  DB_NAME: "cmeproducts_db"
  DB_HOST: "localhost"
  DB_PORT: "5432"
