apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: cme-task
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
